### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by angeloashmore** [kgoggin/xstate-redux#1]
Hi @kgoggin, it doesn't look like this package is published to NPM. Is it possible to publish? This looks very interesting and I want to give it a try.

Thanks!

**Comment by kgoggin** [comment]
I didn't end up publishing it because I ended up transitioning away from the project I'd intended to use it on. At this point I don't intend to do much else with it or maintain it, so I didn't want to squat on which I think could end up being a pretty useful package name.

That said, you can still try this out pretty easily - just reference this repo in your project's package.json. [This SO answer provides some more details](https://stackoverflow.com/questions/23210437/npm-install-private-github-repositories-by-dependency-in-package-json).

And, if you're interested in taking it over I'd be happy to transfer it over!
